### ISSUE TITLE
Enhancement: system setting to pre-select mediasource

### ISSUE THREAD

**Issue by MedusaDelft** [bezumkin/BannerY#23]
I would like to see an option in system settings to pre-select a media source, so my client doesn't upload a new logo in the wrong direction by mistake.
Maybe even make the mediasource unchangable.

**Comment by bezumkin** [comment]
Try to create system setting with key `bannery.media_source` and specify id of needed media source.

**Comment by MedusaDelft** [comment]
I've created the setting, but it still opens with the 'Filesystem' as media source.

**Comment by MedusaDelft** [comment]
"bannery_media_source" as a setting works now. Thanks.
