### ISSUE TITLE
Images not shown in maintenance list if extension is in uppercase

### ISSUE THREAD

**Issue by MedusaDelft** [bezumkin/BannerY#24]
My client uploaded a couple of logo's with the extension  .JPG  instead of  .jpg
The first images are not shown in the list of ad's (Extra's - Banner Y), where the images with the lowercase extension are shown.

Or am I doing something wrong?

Revo 2.3.3

**Comment by bezumkin** [comment]
Could you please try [this fix](https://github.com/bezumkin/BannerY/commit/e513b9d581e6477e88178f106ec4df6931ccdfa6)?

**Comment by MedusaDelft** [comment]
Great, this works! Thanks!
